name = "luckyrong-router"
main = "workers/router.js"
compatibility_date = "2024-01-01"
workers_dev = false

routes = [
  { pattern = "luckyrong.ysoseri.us/*", zone_name = "ysoseri.us" },
  { pattern = "ysoseri.us/api/*", zone_name = "ysoseri.us" }
]

[[d1_databases]]
binding = "DB"
database_name = "together-time"
database_id = "9d9f2d28-d04d-41bb-91f0-d0d4a055ae3e"

[[d1_databases]]
binding = "TIMELINE_DB"
database_name = "timeline"
database_id = "5c8f922d-a683-4888-b1a6-21a8603b111c"

[[r2_buckets]]
binding = "TIMELINE_MEDIA"
bucket_name = "timeline-media"

[vars]
JWT_SECRET = "together-time-luckyrong-2026"
